### ISSUE TITLE
一个很离奇的XML崩溃报错

### ISSUE THREAD

**Issue by DubheBroken** [YoKeyword/IndexableRecyclerView#105]
XML及其相关的Activity、Fragment、Adapter什么的都已经半个月没动过了。今天突然闪退。上一个版本已经装在手机上的可以正常运行，再重新build一遍就不行了，闪退。回滚旧的代码照样报错。怀疑IDE问题，重装Android Studio重新下sdk，错误依旧。
报错信息：

> 2019-06-24 17:12:30.835 20138-20138/com.kalanqicar.xiche E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.kalanqicar.xiche, PID: 20138
>     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kalanqicar.xiche/com.kalanqicar.xiche.mvp.view.activity.CarArtistSelectActivity}: android.view.InflateException: Binary XML file line #48: Binary XML file line #48: Error inflating class me.yokeyword.indexablerv.IndexableLayout
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3194)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
>         at android.app.ActivityThread.-wrap12(Unknown Source:0)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
>         at android.os.Handler.dispatchMessage(Handler.java:108)
>         at android.os.Looper.loop(Looper.java:166)
>         at android.app.ActivityThread.main(ActivityThread.java:7425)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
>      Caused by: android.view.InflateException: Binary XML file line #48: Binary XML file line #48: Error inflating class me.yokeyword.indexablerv.IndexableLayout
>      Caused by: android.view.InflateException: Binary XML file line #48: Error inflating class me.yokeyword.indexablerv.IndexableLayout
>      Caused by: java.lang.reflect.InvocationTargetException
>         at java.lang.reflect.Constructor.newInstance0(Native Method)
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
>         at android.view.LayoutInflater.createView(LayoutInflater.java:658)
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
>         at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
>         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
>         at android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
>         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
>         at android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
>         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
>         at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
>         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
>         at com.kalanqicar.xiche.base.BaseActivity.onCreate(BaseActivity.java:55)
>         at android.app.Activity.performCreate(Activity.java:7372)
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
>         at android.app.ActivityThread.-wrap12(Unknown Source:0)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
>         at android.os.Handler.dispatchMessage(Handler.java:108)
>         at android.os.Looper.loop(Looper.java:166)
>         at android.app.ActivityThread.main(ActivityThread.java:7425)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
>      Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lme/yokeyword/indexablerecyclerview/R$styleable;
>         at me.yokeyword.indexablerv.IndexableLayout.init(IndexableLayout.java:325)
>         at me.yokeyword.indexablerv.IndexableLayout.<init>(IndexableLayout.java:134)
>         at me.yokeyword.indexablerv.IndexableLayout.<init>(IndexableLayout.java:129)
>         at java.lang.reflect.Constructor.newInstance0(Native Method) 
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
>         at android.view.LayoutInflater.createView(LayoutInflater.java:658) 
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801) 
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741) 
>         at android.view.LayoutInflater.rInflate(LayoutInflater.java:874) 
>         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835) 
>         at android.view.LayoutInflater.rInflate(LayoutInflater.java:877) 
>         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835) 
>         at android.view.LayoutInflater.rInflate(LayoutInflater.java:877) 
>         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835) 
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
>         at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
>         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
>         at com.kalanqicar.xiche.base.BaseActivity.onCreate(BaseActivity.java:55) 
>         at android.app.Activity.performCreate(Activity.java:7372) 
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218) 
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147) 
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302) 
>         at android.app.ActivityThread.-wrap12(Unknown Source:0) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891) 
>         at android.os.Handler.dispatchMessage(Handler.java:108) 
>         at android.os.Looper.loop(Looper.java:166) 
>         at android.app.ActivityThread.main(ActivityThread.java:7425) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
> 2019-06-24 17:12:30.835 20138-20138/com.kalanqicar.xiche E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "me.yokeyword.indexablerecyclerview.R$styleable" on path: DexPathList[[zip file "/data/app/com.kalanqicar.xiche-R-sCsO0rIujZCo7HnuHnNA==/base.apk"],nativeLibraryDirectories=[/data/app/com.kalanqicar.xiche-R-sCsO0rIujZCo7HnuHnNA==/lib/arm, /data/app/com.kalanqicar.xiche-R-sCsO0rIujZCo7HnuHnNA==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /product/lib]]
>         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
>         	... 32 more
> 2019-06-24 17:12:30.837 20138-20267/com.kalanqicar.xiche D/TelephonyManager: getCellLocation calling app is com.kalanqicar.xiche
> 2019-06-24 17:12:31.587 20138-20138/com.kalanqicar.xiche I/Process: Sending signal. PID: 20138 SIG: 9

#### XML

> <?xml version="1.0" encoding="utf-8"?>
> <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
>     xmlns:app="http://schemas.android.com/apk/res-auto"
>     xmlns:tools="http://schemas.android.com/tools"
>     android:layout_width="match_parent"
>     android:layout_height="match_parent"
>     android:background="@color/white"
>     android:focusable="true"
>     android:focusableInTouchMode="true"
>     android:orientation="vertical">
> 
>     <LinearLayout
>         android:layout_width="match_parent"
>         android:layout_height="wrap_content"
>         android:elevation="8dp"
>         android:orientation="vertical">
> 
>         <include
>             layout="@layout/app_head"
>             android:layout_width="match_parent"
>             android:layout_height="wrap_content" />
> 
>         <FrameLayout
>             android:layout_width="match_parent"
>             android:layout_height="wrap_content"
>             android:background="#393B43"
>             android:elevation="8dp"
>             android:paddingStart="12dp"
>             android:paddingTop="4dp"
>             android:paddingEnd="12dp"
>             android:paddingBottom="9dp">
> 
>             <EditText
>                 android:id="@+id/edit_search"
>                 android:layout_width="match_parent"
>                 android:layout_height="wrap_content"
>                 android:layout_gravity="center"
>                 android:background="@drawable/bg_searchbar_white"
>                 android:gravity="center_vertical|start"
>                 android:hint="搜索车辆品牌"
>                 android:paddingStart="16dp"
>                 android:paddingTop="8dp"
>                 android:paddingEnd="16dp"
>                 android:paddingBottom="8dp"
>                 android:textColorHint="#ffb9b9b9"
>                 android:textCursorDrawable="@null"
>                 android:textSize="11sp" />
> 
>         </FrameLayout>
>     </LinearLayout>
> 
>     <FrameLayout
>         android:layout_width="match_parent"
>         android:layout_height="match_parent">
> 
>         <me.yokeyword.indexablerv.IndexableLayout
>             android:id="@+id/indexablelayout_brand"
>             android:layout_width="match_parent"
>             android:layout_height="match_parent"
>             android:layout_marginBottom="12dp"
>             app:indexBar_layout_width="24dp"
>             app:indexBar_selectedTextColor="#393B43"
>             app:indexBar_textColor="#949494"
>             app:indexBar_textSize="14sp"
>             app:indexBar_textSpace="6dp" />
> 
>         <fragment
>             android:id="@+id/search_fragment"
>             class="com.kalanqicar.xiche.mvp.view.fragment.SearchFragment"
>             android:layout_width="match_parent"
>             android:layout_height="match_parent" />
>     </FrameLayout>
> 
> 
> </LinearLayout>

#### gradle

> compileSdkVersion 27
>     defaultConfig {
>         multiDexEnabled true
>         applicationId "com.kalanqicar.xiche"
>         minSdkVersion 16
>         targetSdkVersion 27
>         versionCode 31
>         versionName "1.3.15"
>         ndk {
>             abiFilters 'armeabi-v7a', 'x86'//, 'armeabi-v7a', 'x86_64', 'arm64-v8a'
>         }
>     }
> 
>  implementation 'com.android.support:appcompat-v7:27.1.1'
>     implementation 'com.android.support.constraint:constraint-layout:1.1.3'
>     implementation 'com.android.support:design:27.1.1'
>     implementation 'com.android.support:recyclerview-v7:27.1.1'
> 
>  //首字母分类列表
>     implementation 'me.yokeyword:indexablerecyclerview:1.3.0'
>     //汉字转拼音,用于模糊搜索
>     implementation 'com.github.promeg:tinypinyin:2.0.3'

**Comment by DubheBroken** [comment]
找到原因了，导入其他库的时候有一个库导了两次不一样的版本，导致appcompat包的版本号混乱了。
