### ISSUE TITLE
程序有两个bug 直接闪退。

### ISSUE THREAD

**Issue by XieZhiFa** [YoKeyword/IndexableRecyclerView#19]
1.示例代码中， 选择联系人偶尔会一直显示旋转框，不消失。
2.偶尔会抛出以下异常：

com.yokeyword.indexablelistview.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: com.yokeyword.indexablelistview.sample, PID: 13239
                                                                                        java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(-1, class android.widget.ListView) with Adapter(class android.widget.HeaderViewListAdapter)]
                                                                                            at android.widget.ListView.layoutChildren(ListView.java:1562)
                                                                                            at android.widget.AbsListView.onLayout(AbsListView.java:2151)
                                                                                            at android.view.View.layout(View.java:15685)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                            at android.view.View.layout(View.java:15685)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                                            at android.view.View.layout(View.java:15685)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                            at android.view.View.layout(View.java:15685)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                            at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
                                                                                            at android.view.View.layout(View.java:15685)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                            at android.view.View.layout(View.java:15685)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                                            at android.view.View.layout(View.java:15685)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                            at android.view.View.layout(View.java:15685)
                                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2123)
                                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1880)
                                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1098)
                                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5933)
                                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:775)
                                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:588)
                                                                                            at android.view.Choreographer.doFrame(Choreographer.java:558)
                                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:761)
                                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5290)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

3.优化建议： 选择城市“定”没有显示完全，而且只能用文字，不能用定位的图标。

**Comment by XieZhiFa** [comment]
1.示例代码中， 选择联系人偶尔会一直显示旋转框，不消失。
2.偶尔会抛出以下异常：

com.yokeyword.indexablelistview.sample E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.yokeyword.indexablelistview.sample, PID: 13239
java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(-1, class android.widget.ListView) with Adapter(class android.widget.HeaderViewListAdapter)]
at android.widget.ListView.layoutChildren(ListView.java:1562)
at android.widget.AbsListView.onLayout(AbsListView.java:2151)
at android.view.View.layout(View.java:15685)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:15685)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
at android.view.View.layout(View.java:15685)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:15685)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
at android.view.View.layout(View.java:15685)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:15685)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
at android.view.View.layout(View.java:15685)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
at android.view.View.layout(View.java:15685)
at android.view.ViewGroup.layout(ViewGroup.java:5039)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2123)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1880)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1098)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5933)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:775)
at android.view.Choreographer.doCallbacks(Choreographer.java:588)
at android.view.Choreographer.doFrame(Choreographer.java:558)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:761)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5290)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

3.优化建议： 选择城市“定”没有显示完全，而且只能用文字，不能用定位的图标。

**Comment by YoKeyword** [comment]
感谢反馈，是最新版引起的问题吗？
该库国庆前后会进行大版本的重构，用RecyclerView代替ListView，会关注你的建议，感谢～

**Comment by XieZhiFa** [comment]
是的，今天下载的应该是最新的版本， 运行了一下， 发现这几个问题。
另外提几个建议：
1. 数据匹配规则建议可以自定义，比如可以使用完全匹配，可以以关键字开关，或者可以多个关键字匹配。
2. 汉字只是做了字母分类， 但是没有按name排序。
3. item没有多选功能， 建议可以用单选跟多选功能。
4.右边的滑动条文字没有显示全demo中的“定”定没有显示那个点。

以下是本人的一些修改：
1. 关于闪退，把bindDatas中的if (mContext instanceof Activity)  注释掉，只保存else中的代码不会闪退， 但是进入界面的时候会有一点点卡顿。
希望可以跟你交流一下。

**Comment by YoKeyword** [comment]
感谢建议🙏   重构时会考虑这些建议哒～
if (mContext instanceof Activity) 注释掉确实不会出现那个BUG，但是在需要重复绑定数据的场景下不适合，因为是在主线程执行了排序功能，这块我回头再考虑下

**Comment by YoKeyword** [comment]
进行非常大幅度的重构；从ListView更改为RecyclerView的实现
性能优化，更易使用的API，更易拓展的HeaderView等等   :)

后续更新会参考你的反馈哒～
