### ISSUE TITLE
不好使啊各种报错

### ISSUE THREAD

**Issue by fangithubgithub** [YoKeyword/IndexableRecyclerView#34]
02-20 14:06:06.709 818-3775/? E/ActivityManager: Invalid thumbnail dimensions: 0x0
02-20 14:06:06.759 818-3617/? E/ActivityManager: Invalid thumbnail dimensions: 0x0
02-20 14:06:10.539 6820-6820/? E/MarketLocalAppManager: getDetailAppInfo null: com.wyys.seller
02-20 14:06:10.629 6820-7141/? E/MarketDataParser: [AppList] JSON : list is null
                                                   No value for miuiApp
                                                   
                                                   [ 02-20 14:06:10.629 14319:14319 W/         ]
                                                   [ColorAdjust] Set temp_prefer temp_ce!
02-20 14:06:10.709 6820-7106/? E/MarketDataParser: [AppList] JSON : list is null
                                                   No value for listApp
02-20 14:06:10.999 818-4948/? E/ActivityManager: Invalid thumbnail dimensions: 0x0
02-20 14:06:11.059 14337-14347/? E/art: Failed sending reply to debugger: Broken pipe
02-20 14:06:19.099 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=3.97 rxSuccessRate=5.16 targetRoamBSSID=any RSSI=-42
02-20 14:06:19.099 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:06:39.099 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.57 rxSuccessRate=5.99 targetRoamBSSID=any RSSI=-44
02-20 14:06:39.099 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:06:54.709 14337-14337/com.wyys.seller E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.wyys.seller, PID: 14337
                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wyys.seller/com.wyys.seller.ProvingActivity}: android.view.InflateException: Binary XML file line #29: Error inflating class me.yokeyword.indexablerv.IndexableLayout
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2342)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404)
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5290)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
                                                                  Caused by: android.view.InflateException: Binary XML file line #29: Error inflating class me.yokeyword.indexablerv.IndexableLayout
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:637)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:810)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:508)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:418)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
                                                                     at com.wyys.seller.ProvingActivity.onCreate(ProvingActivity.java:36)
                                                                     at android.app.Activity.performCreate(Activity.java:6039)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404) 
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5290) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706) 
                                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                                     at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:611)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249) 
                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106) 
                                                                     at com.wyys.seller.ProvingActivity.onCreate(ProvingActivity.java:36) 
                                                                     at android.app.Activity.performCreate(Activity.java:6039) 
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295) 
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404) 
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5290) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706) 
                                                                  Caused by: java.lang.NoSuchMethodError: No static method getColor(Landroid/content/Context;I)I in class Landroid/support/v4/content/ContextCompat; or its super classes (declaration of 'android.support.v4.content.ContextCompat' appears in /data/app/com.wyys.seller-1/base.apk)
                                                                     at me.yokeyword.indexablerv.IndexableLayout.init(IndexableLayout.java:291)
                                                                     at me.yokeyword.indexablerv.IndexableLayout.<init>(IndexableLayout.java:116)
                                                                     at me.yokeyword.indexablerv.IndexableLayout.<init>(IndexableLayout.java:111)
                                                                     at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:611) 
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249) 
                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106) 
                                                                     at com.wyys.seller.ProvingActivity.onCreate(ProvingActivity.java:36) 
                                                                     at android.app.Activity.performCreate(Activity.java:6039) 
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295) 
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404) 
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5290) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706) 
02-20 14:06:54.779 818-3299/? E/InputDispatcher: channel '23d5b9a1 com.wyys.seller/com.wyys.seller.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
02-20 14:06:57.979 818-3299/? E/ActivityManager: Invalid thumbnail dimensions: 0x0
02-20 14:06:59.099 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=5.38 targetRoamBSSID=any RSSI=-40
02-20 14:06:59.099 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:07:19.109 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=2.38 rxSuccessRate=6.49 targetRoamBSSID=any RSSI=-44
02-20 14:07:19.109 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:07:39.109 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=6.03 targetRoamBSSID=any RSSI=-47
02-20 14:07:39.109 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:07:59.109 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=3.04 targetRoamBSSID=any RSSI=-45
02-20 14:07:59.109 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:08:19.109 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=6.06 targetRoamBSSID=any RSSI=-43
02-20 14:08:19.109 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:08:39.119 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=4.09 targetRoamBSSID=any RSSI=-40
02-20 14:08:39.119 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:08:59.119 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=7.15 targetRoamBSSID=any RSSI=-41
02-20 14:08:59.119 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:09:19.119 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.53 rxSuccessRate=4.04 targetRoamBSSID=any RSSI=-46
02-20 14:09:19.119 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:09:39.119 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=3.06 targetRoamBSSID=any RSSI=-45
02-20 14:09:39.129 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:09:55.689 13300-13304/? E/QC-QMI: qmi_client [13300] 59: failed to locate client data
02-20 14:09:55.699 436-436/? E/QC-QMI: qmuxd: RX on fd=28 returned error=0 errno[2:No such file or directory]
02-20 14:09:55.699 436-436/? E/QC-QMI: QMUX qmux_client_id=59 not found in qmux client list, unable to remove
                                       
                                       
                                       [ 02-20 14:09:55.699 15508:15508 W/         ]
                                       [ColorAdjust] gammamode=2, cemode=10
                                       
                                       
                                       [ 02-20 14:09:55.699 15508:15508 W/         ]
                                       [ColorAdjust] temp_gammavalue=2, temp_cevalue=10
                                       
                                       
                                       [ 02-20 14:09:55.699 15508:15508 W/         ]
                                       [ColorAdjust] Don't setGamma!
                                       
                                       
                                       [ 02-20 14:09:55.699 15508:15508 W/         ]
                                       [ColorAdjust] Don't setCe!
                                       
                                       
                                       [ 02-20 14:09:55.719 15508:15508 W/         ]
                                       [ColorAdjust] Set temp_prefer temp_ce!
02-20 14:09:59.129 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.13 rxSuccessRate=1.83 targetRoamBSSID=any RSSI=-44
02-20 14:10:19.129 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=0.97 targetRoamBSSID=any RSSI=-51
02-20 14:10:19.129 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:10:39.129 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=5.66 targetRoamBSSID=any RSSI=-46
02-20 14:10:39.129 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:10:45.469 15625-15625/? E/ApplicationHelper: start process, name=com.miui.player
02-20 14:10:45.569 15625-15670/? E/RemoteConfigClientBase: com.miui.player: read config success!
02-20 14:10:45.639 15625-15679/? E/FFMPEGPlayer-JNI: JNI_OnLoad
02-20 14:10:45.799 15690-15690/? E/ApplicationHelper: start process, name=com.miui.player:remote
02-20 14:10:59.139 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.63 rxSuccessRate=3.64 targetRoamBSSID=any RSSI=-45
02-20 14:10:59.139 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:11:19.139 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=9.54 targetRoamBSSID=any RSSI=-49
02-20 14:11:19.139 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:11:39.139 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=3.04 targetRoamBSSID=any RSSI=-43
02-20 14:11:39.139 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:11:59.139 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.91 rxSuccessRate=2.49 targetRoamBSSID=any RSSI=-43
02-20 14:11:59.139 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:12:19.149 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=3.00 targetRoamBSSID=any RSSI=-47
02-20 14:12:19.149 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:12:39.149 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=3.91 targetRoamBSSID=any RSSI=-43
02-20 14:12:39.149 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:12:59.149 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=1.23 targetRoamBSSID=any RSSI=-41
02-20 14:12:59.149 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:13:19.159 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=6.74 targetRoamBSSID=any RSSI=-47
02-20 14:13:19.159 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:13:39.159 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=7.39 targetRoamBSSID=any RSSI=-46
02-20 14:13:39.159 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:13:59.159 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.31 rxSuccessRate=2.63 targetRoamBSSID=any RSSI=-44
02-20 14:13:59.159 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:14:19.169 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=2.00 rxSuccessRate=13.40 targetRoamBSSID=any RSSI=-45
02-20 14:14:19.169 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:14:39.169 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=7.13 targetRoamBSSID=any RSSI=-45
02-20 14:14:39.169 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:14:59.169 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.06 rxSuccessRate=2.95 targetRoamBSSID=any RSSI=-46
02-20 14:14:59.169 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:15:19.169 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=4.17 targetRoamBSSID=any RSSI=-48
02-20 14:15:19.169 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412
02-20 14:15:39.179 818-3308/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=6.79 targetRoamBSSID=any RSSI=-43
02-20 14:15:39.179 818-3308/? E/WifiStateMachine: WifiStateMachine starting scan for "angle2016"-WPA_PSK with 2412

**Comment by fangithubgithub** [comment]
02-20 14:16:38.229 16567-16567/com.wyys.seller E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.wyys.seller, PID: 16567
                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wyys.seller/com.wyys.seller.ProvingActivity}: android.view.InflateException: Binary XML file line #29: Error inflating class me.yokeyword.indexablerv.IndexableLayout
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2342)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404)
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5290)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
                                                                  Caused by: android.view.InflateException: Binary XML file line #29: Error inflating class me.yokeyword.indexablerv.IndexableLayout
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:637)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:810)
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:508)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:418)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
                                                                     at com.wyys.seller.ProvingActivity.onCreate(ProvingActivity.java:36)
                                                                     at android.app.Activity.performCreate(Activity.java:6039)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404) 
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5290) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706) 
                                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                                     at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:611)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249) 
                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106) 
                                                                     at com.wyys.seller.ProvingActivity.onCreate(ProvingActivity.java:36) 
                                                                     at android.app.Activity.performCreate(Activity.java:6039) 
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295) 
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404) 
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5290) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706) 
                                                                  Caused by: java.lang.NoSuchMethodError: No static method getColor(Landroid/content/Context;I)I in class Landroid/support/v4/content/ContextCompat; or its super classes (declaration of 'android.support.v4.content.ContextCompat' appears in /data/app/com.wyys.seller-1/base.apk)
                                                                     at me.yokeyword.indexablerv.IndexableLayout.init(IndexableLayout.java:291)
                                                                     at me.yokeyword.indexablerv.IndexableLayout.<init>(IndexableLayout.java:116)
                                                                     at me.yokeyword.indexablerv.IndexableLayout.<init>(IndexableLayout.java:111)
                                                                     at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:611) 
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:418) 
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249) 
                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106) 
                                                                     at com.wyys.seller.ProvingActivity.onCreate(ProvingActivity.java:36) 
                                                                     at android.app.Activity.performCreate(Activity.java:6039) 
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295) 
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404) 
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:135) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5290) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

**Comment by fangithubgithub** [comment]
求解答

**Comment by YoKeyword** [comment]
> ComponentInfo{com.wyys.seller/com.wyys.seller.ProvingActivity}: android.view.InflateException: Binary XML file line #29: Error inflating class me.yokeyword.indexablerv.IndexableLayout

ProvingActivity的xml布局代码贴一下

**Comment by fangithubgithub** [comment]
就是你那个代码沾过去的

**Comment by YoKeyword** [comment]
Demo看下能跑吗？  能跑的话仔细检查下代码～

**Comment by fangithubgithub** [comment]
demo能跑弄到自己的项目里不好使

**Comment by fangithubgithub** [comment]
你那个pickactivity我可以放到fragment里，我的底部切换时4个fragment

**Comment by fangithubgithub** [comment]
还有那个sdk版本我感觉那个可能太高，v4v7的libs我的好像放不了那么高，我用httpclient解析的最高到5.1，你那是6.0的么

**Comment by YoKeyword** [comment]
建议仔细检查下XML的29行附近  或者贴代码；   和SDK应该没关系的

**Comment by fangithubgithub** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:background="@android:color/white"
              android:orientation="vertical">

    <android.support.v7.widget.SearchView
        android:id="@+id/searchview"
        android:layout_width="match_parent"
        android:layout_height="42dp"
        android:layout_marginBottom="4dp"
        android:layout_marginLeft="16dp"
        android:layout_marginRight="16dp"
        android:layout_marginTop="8dp"
        android:background="#f3f3f3"
        android:focusable="false"
        android:focusableInTouchMode="false"
        android:textColor="#757575"
        app:iconifiedByDefault="false"
        app:queryBackground="@null"
        app:queryHint="请输入关键字"/>

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <me.yokeyword.indexablerv.IndexableLayout
            android:id="@+id/indexableLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:indexBar_background="#08000000"
            app:indexBar_layout_width="24dp"
            app:indexBar_textColor="@android:color/black"
            app:indexBar_textSpace="8dp"/>

        <fragment
            android:id="@+id/search_fragment"
            class="me.yokeyword.sample.city.SearchFragment"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>

        <FrameLayout
            android:id="@+id/progress"
            android:layout_width="match_parent"
            android:background="@android:color/white"
            android:layout_height="match_parent">

            <ProgressBar
                android:layout_width="56dp"
                android:layout_height="56dp"
                android:layout_gravity="center"/>
        </FrameLayout>
    </FrameLayout>
</LinearLayout>

**Comment by YoKeyword** [comment]
<fragment>标签里的class="me.yokeyword.sample.city.SearchFragment"

这个Fragment你没有这个类吧， 要写你自己的Fragment类

**Comment by fangithubgithub** [comment]
我是先粘的你的，难道不好使么

**Comment by YoKeyword** [comment]
我的是Demo。。。。  实际情况当然按照README来集成

<fragment>标签里的name, class属性 需要填写项目中存在的类名

**Comment by fangithubgithub** [comment]
那个我知道，都根据我的实际项目改的，

**Comment by fangithubgithub** [comment]
但是他就是不好使

**Comment by fangithubgithub** [comment]
就是正常按自己的项目改掉能改的类和名也应该好使啊

**Comment by fangithubgithub** [comment]
你的改了就一点就蹦报错了

**Comment by YoKeyword** [comment]
最终...找到原因了吗？    是class名的问题吗？  复制粘贴少用，那个是Demo，和你场景可能不同，自己集成下

**Comment by fangithubgithub** [comment]
改不了你的，

**Comment by fangithubgithub** [comment]
用别人的了

**Comment by fangithubgithub** [comment]
那个有点不妥

**Comment by YoKeyword** [comment]
OK
