### ISSUE TITLE
关于item_contact.xml布局问题

### ISSUE THREAD

**Issue by MarkerBrother** [YoKeyword/IndexableRecyclerView#60]
自己根据大哥的代码改了下，用大哥的数据模拟没问题。但是用自己项目获取数据的时候，发现总是报这个错误：
04-15 15:08:37.250 22714-22714/com.aspsine.swipetoloadlayoutdemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.aspsine.swipetoloadlayoutdemo, PID: 22714
                                                                                   android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
                                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:637)
                                                                                       at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
                                                                                       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:686)
                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:745)
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:486)
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:418)
                                                                                       at com.eiscp.android.main.surface.ContactAdapter.onCreateContentViewHolder(ContactAdapter.java:33)
                                                                                       at me.yokeyword.indexablerv.RealAdapter.onCreateViewHolder(RealAdapter.java:92)
                                                                                       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6290)
                                                                                       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5478)
                                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5363)
                                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5359)
                                                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2141)
                                                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1525)
                                                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1488)
                                                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:585)
                                                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3506)
                                                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3254)
                                                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3767)
                                                                                       at android.view.View.layout(View.java:15691)
                                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                       at android.view.View.layout(View.java:15691)
                                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                       at android.view.View.layout(View.java:15691)
                                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                                       at android.view.View.layout(View.java:15691)
                                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
                                                                                       at android.view.View.layout(View.java:15691)
                                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                                       at android.view.View.layout(View.java:15691)
                                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                       at android.view.View.layout(View.java:15691)
                                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                       at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
                                                                                       at android.view.View.layout(View.java:15691)
                                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                                       at android.view.View.layout(View.java:15691)
                                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                                       at android.view.View.layout(View.java:15691)
04-15 15:08:37.260 22714-22714/com.aspsine.swipetoloadlayoutdemo I/Process: Sending signal. PID: 22714 SIG: 9

最后把item_contact.xml下的<RelativeLayout    ></RelativeLayout>中的
android:background="?attr/selectableItemBackground"
这一行给去掉了，然后才可以正常运行，但是运行后的点击事件中没有了那个类似水波纹的效果，现在是啥效果都没有了。如果没有toast根本就发现不了点击的。请问下这是怎么情况呢？

**Comment by YoKeyword** [comment]
`android:background="?attr/selectableItemBackground"` 属性在 5.0+设备呈现的是水波纹，5.0-呈现的是按压效果，这个属性去掉的话就没有点击效果了

看描述应该是加载这个属性出了问题，可以尝试为` android:background="?android:attr/selectableItemBackground"`
