### ISSUE TITLE
越界错误

### ISSUE THREAD

**Issue by Ivolian** [YoKeyword/IndexableRecyclerView#66]
java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
                                                                      at java.util.ArrayList.get(ArrayList.java:413)
                                                                      at me.yokeyword.indexablerv.IndexableLayout$5.onScrolled(IndexableLayout.java:399)
                                                                      at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4618)
                                                                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3679)
                                                                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3323)
                                                                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)

   IndexableLayout.this.mIndexBar.setSelection(firstItemPosition);
                if(IndexableLayout.this.mSticyEnable) {
                    ArrayList list = IndexableLayout.this.mRealAdapter.getItems();
                    if(IndexableLayout.this.mStickyViewHolder != null && list.size() > firstItemPosition) {
                        EntityWrapper wrapper = (EntityWrapper)list.get(firstItemPosition);

当 indexableAdapter setDatas 为空 list 时， firstItemPosition 就返回 -1 了。

**Comment by proud2008** [comment]
也遇到了这个问题 ，期待解决呀

**Comment by proud2008** [comment]
![image](https://user-images.githubusercontent.com/5674136/27623870-0725c382-5c11-11e7-9baa-07231ac05e29.png)

**Comment by YoKeyword** [comment]
v1.2.4已Fix   🍺 :)
