### ISSUE TITLE
问一下总点击返回进入就挂了

### ISSUE THREAD

**Issue by fangithubgithub** [YoKeyword/IndexableRecyclerView#70]
Process: com.wyys.faction, PID: 16637
                                                                  java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                                      at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
                                                                      at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1860)
                                                                      at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:649)
                                                                      at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:609)
                                                                      at com.wyys.faction.AdressActivity.initSearch(AdressActivity.java:334)
                                                                      at com.wyys.faction.AdressActivity.Data(AdressActivity.java:209)
                                                                      at com.wyys.faction.AdressActivity.access$800(AdressActivity.java:48)
                                                                      at com.wyys.faction.AdressActivity$8.handleMessage(AdressActivity.java:306)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5290)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteIn

**Comment by YoKeyword** [comment]
在Activity不可见时，执行了Fragment事务，解决方式可以看下[这里](http://www.jianshu.com/p/d9143a92ad94)
